[130] feat: added attribute tabs for admin page
hack4impact-calpoly/veggie-rescue pull request #143
Opened 2023-02-07 10:29 UTC by oprylord

## Developer: Jerry Tang

### Pull Request Summary

added attribute tabs for the admin page

### Pull Request Checklist

- [ ] Code is neat, readable, and works
- [ ] Comments are appropriate
- [ ] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [ ] The developer name is specified
- [ ] The summary is completed
- [ ] Ask for a review in communication channels

### Reviewer Checklist - PULL REQUEST REVIEWER ONLY

IMPORTANT: The rest of the sections in this checklist should only be filled out by authorized pull request reviewers. If you are the individual contributor, do not fill out the rest of the fields or check the boxes.

## Reviewer: Full Name

NOTE: Pull requests should only be merged when all boxes are checked.

- [ ] Assign yourself as reviewer if not assigned
- [ ] The reviewer name is specified
- [ ] The code is fully reviewed
- [ ] Meaningful feedback is given
- [ ] Let developer know a review has been made

2023-02-09 08:29 UTC, ishaansathaye requested changes
Hey, this is great work! I ran your branch and everything ran smoothly and the tabs look amazing.

However, there are now a few things that need to be changed/modified per the specifications that we decided. In the Github Wiki under Docs->Data Samples you will find the doc for Updated Field Names. Essentially the naming of the tabs needs to be in line with that doc. Also, from that doc there needs to be one more tab added to the row called Food Distribution Model.

The naming conventions include:
- Recipients
    - Demographic Name -> Demographic Served
    - Add Food Distribution Model button
    - Entity Type -> Organizational Structure

So, for the extra button that is needed, from a design standpoint, have the button on the same row but the spacing decreases (but equal) between all the tabs. And this button would only be for Recipients so it would not show up for Donors.

2023-02-13 22:09 UTC, oprylord commented
Fixed!

2023-02-16 08:26 UTC, ishaansathaye requested changes
Perfect! There are just some prettier and eslint problems with AdminDataScreen.tsx. Just resolve those and this will ready to merge.

2023-02-24 00:54 UTC, ishaansathaye approved these changes

2023-02-24 01:36 UTC, merged