[138] refactor: modified service and slice to be compatible with new schemas
hack4impact-calpoly/veggie-rescue pull request #158
Opened 2023-03-02 18:29 UTC by canbarci

## Developer: Chloe Anbarcioglu

### Pull Request Summary

I modified service and slice to be compatible with new schemas. I also fixed eslint errors.

Describe the purpose of your pull request and the steps you took to implement it. If this is a frontend issue include screenshots. 

### Pull Request Checklist 
(Acutally check off the boxes to make sure you've done everything) 

- [x] Link your issue
- [x] PR title is in the format `[issue #] type: description`
- [x] Code is neat, readable, and works
- [x] Comments are appropriate
- [x] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [x] Developer name is specified
- [x] Summary is completed
- [x] Request a review from your tech leads 

AFTER REVIEW 
- Make sure you respond to all of the reviewer's feedback.
- If they make proposed changes either accept them or respond with questions/clarification.
- If they make comments either respond, or if you fixed the issue, resolve the conversation 

### Reviewer Checklist - PULL REQUEST REVIEWER ONLY

IMPORTANT: The rest of the sections in this checklist should only be filled out by authorized pull request reviewers. If you are the individual contributor, do not fill out the rest of the fields or check the boxes.

## Reviewer: Full Name

NOTE: Pull requests should only be merged when all boxes are checked.

- [ ] Assign yourself as reviewer if not assigned
- [ ] The reviewer name is specified
- [ ] The code is fully reviewed
- [ ] Meaningful feedback is given
- [ ] Let developer know a review has been made

2023-03-02 18:56 UTC, esauerbo requested changes
Great work on this! 

There were just a few things then we'll be good to ship. I left a comment about the naming conventions, and also I'm still seeing some eslint/prettier errors on my end.

Can you try running `eslint --fix <path-to-file>` and `prettier --write <path-to-file>` for each of the files you edited? That will fix most things automatically and it will print out anything you need to fix manually.

2023-03-02 18:56 UTC, esauerbo commented on frontend/src/components/Dashboard/Dashboard.tsx
>  interface pickupObject {
Can you change the names of these? The error message means that they want the first letter to be capitalized

2023-03-07 03:06 UTC, esauerbo approved these changes
lgtm! Great work on this Chloe.

2023-03-09 23:58 UTC, ishaansathaye approved these changes

2023-03-13 22:03 UTC, merged